### ISSUE TITLE
Error while running the node. "GenICam_3_1_Basler_pylon::RuntimeException"

### ISSUE THREAD

**Issue by FiIipe** [fhwedel-hoe/pylon_instant_camera#4]
Hello, 

I was trying to run the pylon_instant_camera node and I'm getting the following error: 
```
[INFO] [1643317249.693390707] [pylon_instant_camera]: Constructing camera object for full name [], user defined name [], IP address [].
terminate called after throwing an instance of 'GenICam_3_1_Basler_pylon::RuntimeException'
```

Command that I used: ros2 run pylon_instant_camera node

Any help is appreciated.

Cheers, 
Filipe

**Comment by fhwedel-hoe** [comment]
Something in the [PylonCamera](https://github.com/fhwedel-hoe/pylon_instant_camera/blob/3fc4051ff56be8a84885d351628a42e951dfeef8/src/main.cpp#L47) constructor is throwing an exception. Unfortunately, I did not surround that with a `try…catch` and the details about the error are not printed. :(

I do not know whether I can add it within this week. If it is urgent, feel free to try yourself.

Which OS are you on? Is it a USB or GigE camera?

**Comment by fhwedel-hoe** [comment]
Does using d05acd8 yield more information?

**Comment by FiIipe** [comment]
Hi @fhwedel-hoe, 

I am using ubuntu 18.04 and I also tested in ubuntu 20.04. I tested again and it is running fine, no problems. 

Cheers
